version: 2

sources:
  - name: stg
    schema: stg
    tables:
      - name: sales
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 2, period: day}
        loaded_at_field: loaded_at  # Make sure this field exists in your table
      - name: inventory
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 2, period: day}
        loaded_at_field: loaded_at  # Make sure this field exists in your table
  - name: dw
    schema: dw
    tables:
      - name: calendar
      - name: stores
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 2, period: day}
        loaded_at_field: loaded_at  # Make sure this field exists in your table
      - name: products
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 2, period: day}
        loaded_at_field: loaded_at  # Make sure this field exists in your table
